### ISSUE TITLE
Add ability to create dropdown-menu for linked_sites

### ISSUE THREAD

**Issue by JuLiaN47V** [JuLiaN47V/association-as-code#7]
## Problem
For linked_sites in the same category, it is not possible to create a dropdown-menu with config file.

## Feature
Add ability to configure a dropdown-menu for linked_sites.  
Config Example:
```yaml
linked_sites:
  - name: "Cloud"
    url: "https://cloud.example.com/"
    type: "single"
  - name: "Files"
    type: "catecory"
    sites:
      - name: "Application"
         url: "https://cloud.example.com/files/application.doc"
      - name: "Rental"
         url: "https://cloud.example.com/files/rental.doc"
```
